AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ExecutionRoleArn:
    Type: String
    Default: arn:aws:iam::117819748843:role/lake-freeze-lambda-role

  DeploymentZone:
    Type: String
    Default: deployment-zone-117819748843

  EmrZone:
    Type: String
    Default: emr-zone-117819748843-us-east-1

Resources:
  ETLJobTrigger:
    Type: AWS::Events::Rule
    Properties: 
      # Description: String
      Name: WeatherETLJobTrigger
      RoleArn: !Ref ExecutionRoleArn
      ScheduleExpression: "cron(0 6 * * ? *)"
      State: ENABLED
      Targets:
        - Id: ETLStepFunction
          Arn: !GetAtt StepFunctionStateMachine.Arn
          Input: "{\n  \"input\": \"{}\"\n}"
          RetryPolicy:
            MaximumEventAgeInSeconds: 300
            MaximumRetryAttempts: 3
          RoleArn: !Ref ExecutionRoleArn

  EMRServerlessApplication:
    Type: AWS::EMRServerless::Application
    Properties: 
      Name: WeatherETLApplication
      Architecture: ARM64
      AutoStartConfiguration: 
        Enabled: true
      AutoStopConfiguration: 
        Enabled: true
        IdleTimeoutMinutes: 1
      MaximumCapacity: 
        Cpu: 4vCPU
        Disk: 100GB
        Memory: 16GB
      ReleaseLabel: "emr-6.10.0"
      Type: Spark
  
  StepFunctionStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: EMRWeatherETLJobStateMachine
      RoleArn: !Ref ExecutionRoleArn
      Definition: {
            "Comment": "Runs EMR Serverless job for Weather ETL",
            "StartAt": "StartJobRun",
            "States": {
                "StartJobRun": {
                  "Type": "Task",
                  "End": true,
                  "Parameters": {
                      "Name": "Weather ETL",
                      "ClientToken.$": "States.UUID()",
                      "ApplicationId": !Ref EMRServerlessApplication,
                      "ExecutionRoleArn": !Ref ExecutionRoleArn,
                      "JobDriver": {
                        "SparkSubmit": {
                            "EntryPoint": !Sub "s3://${DeploymentZone}/weather_etl/spark_entrypoint.py",
                            "SparkSubmitParameters": !Sub "
                                --driver-memory 2G 
                                --driver-cores 2 
                                --num-executors 1 
                                --executor-memory 2G
                                --executor-cores 2
                                --conf spark.dynamicAllocation.enabled=false
                                --conf spark.archives=s3://${DeploymentZone}/weather_etl/pyspark_env.tar.gz
                                --conf spark.emr-serverless.driverEnv.PYSPARK_DRIVER_PYTHON=/home/hadoop/pyspark_env/bin/python
                                --conf spark.emr-serverless.driverEnv.PYSPARK_PYTHON=/home/hadoop/pyspark_env/bin/python
                                --conf spark.executorEnv.PYSPARK_PYTHON=/home/hadoop/pyspark_env/bin/python
                              "
                                                              
                                
                              # --conf spark.jars.packages=org.postgresql:postgresql:42.6.0
                        }
                      },
                      "ConfigurationOverrides": {
                        "MonitoringConfiguration": {
                          "S3MonitoringConfiguration": {
                            "LogUri": !Sub "s3://${EmrZone}/logging/"
                          }
                        }
                      },
                      "ExecutionTimeoutMinutes": 20
                  },
                  "Resource": "arn:aws:states:::aws-sdk:emrserverless:startJobRun"
                }
            }
        }

      




            
