
Parameters:
  ExecutionRoleArn:
    Type: String
    Default: arn:aws:iam::117819748843:role/lake-freeze-lambda-role

  DeploymentZone:
    Type: String
    Default: deployment-zone-117819748843

Resources:

  EMRServerlessApplication:
    Type: AWS::EMRServerless::Application
    Properties: 
      Name: WeatherETLApplication
      Architecture: ARM64
      AutoStartConfiguration: 
        Enabled: true
      AutoStopConfiguration: 
        Enabled: true
        IdleTimeoutMinutes: 1
      MaximumCapacity: 
        Cpu: vCPU
        Disk: 100GB
        Memory: 16GB
      ReleaseLabel: "emr-6.10.0"
      Type: Spark
  
  ETLJobTrigger:
    Type: AWS::Events::Rule
    Properties: 
      # Description: String
      # EventBusName: default
      # EventPattern: Json
      Name: WeatherETLJobTrigger
      RoleArn: !Ref ExecutionRoleArn
      ScheduleExpression: "cron(0 6 * * ? *)"
      State: Enabled
      Targets:
        - Id: emrjob 
          Arn: "arn:aws:scheduler:::aws-sdk:emrserverless:startJobRun"
          Input: { 
              "Name": "Weather ETL",
              "ApplicationId": !Ref EMRServerlessApplication, 
              "ExecutionRoleArn": !Ref ExecutionRoleArn,
              "JobDriver": {
                "sparkSubmit": {
                  "entryPoint": !Sub "s3://${DeploymentZone}/weather_etl/spark_entrypoint.py"
                  # ,
                  # "entryPointArguements": ,
                  # "sparkSubmitParameters": 
                }
              }
            }