name: Deploy SAM

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "117819748843"

permissions:
  contents: read

jobs:
  deploy_python:
    name: Deploy Python Package
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-python3.7:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Build python package
      #   run: |
      #     pip install awscli
      #     conda install conda-pack
      #     conda create --name pyspark_env --file src/app/requirements.txt python=3.9
      #     conda pack -n pyspark_env -o pyspark_env.tar.gz
      #     aws s3 cp pyspark_env.tar.gz s3://deployment-zone-${AWS_ACCOUNT_ID}/weather_etl/


      - name: Build python package
        run: |
          pip install venv-pack
          python -m venv pyspark_venv
          source pyspark_venv/bin/activate
          pip install ./
          venv-pack -o pyspark_env.tar.gz
          aws s3 cp pyspark_env.tar.gz s3://deployment-zone-${AWS_ACCOUNT_ID}/weather_etl/

      - name: Copy Python files to S3 deployment zone
        run: |
          aws s3 cp spark_entrypoint.py s3://deployment-zone-${AWS_ACCOUNT_ID}/weather_etl/

      


    
  deploy_sam:
    name: Deploy SAM template
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-python3.9:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: SAM build
      run: sam build
      
    - name: SAM deploy
      run: sam deploy


    # - name: SAM build
    #   run: cd lake_freeze_api/ && sam build
      
    # - name: SAM deploy
    #   run: cd lake_freeze_api/ && sam deploy