name: Deploy PySpark ETL job

on:
  push:
    branches: [ "main", "dev" ]

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "117819748843"


  


jobs:
  build:
    name: Build python package
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/sam/build-python3.7:latest #continuumio/miniconda3 #public.ecr.aws/sam/build-python3.9:latest #continuumio/miniconda3 #public.ecr.aws/sam/build-python3.7:latest #public.ecr.aws/sam/build-python3.9:latest #amazonlinux:2 #

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build python package
        run: |
          pip install venv-pack awscli build
          python -m build --sdist ./

      - name: Test python package
        run: |
          pip install pytest
          pip install ./dist/*
          python -m pytest


      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Push to ECR
        if: github.ref == 'refs/heads/main'
        uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ env.AWS_ACCOUNT_ID }}
          repo: weather-etl/pyspark-env
          region: ${{ env.AWS_REGION }}
          tags: latest
          create_repo: false
         

      - name: Copy Python files to S3 deployment zone
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp spark_entrypoint.py s3://deployment-zone-${AWS_ACCOUNT_ID}/weather_etl/
    

  deploy_sam:
    name: Deploy SAM template
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-python3.9:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: SAM build
      run: sam build
      
    - name: SAM deploy
      run: sam deploy --no-fail-on-empty-changeset


    # - name: SAM build
    #   run: cd lake_freeze_api/ && sam build
      
    # - name: SAM deploy
    #   run: cd lake_freeze_api/ && sam deploy