name: Deploy SAM

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "117819748843"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-python3.9:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy Python files to S3 deployment zone
      run: aws s3 cp spark_entrypoint.py s3://deployment-zone-${AWS_ACCOUNT_ID}/weather_etl/

    - name: SAM build
      run: sam build
      
    - name: SAM deploy
      run: sam deploy

    # - name: SAM build
    #   run: cd lake_freeze_api/ && sam build
      
    # - name: SAM deploy
    #   run: cd lake_freeze_api/ && sam deploy